import {defineEventHandler} from "h3";

export default defineEventHandler((event) => {
    return [
        {
            id: 1,
            img: '@/assets/product_big_1.png',
            title: 'BXC',
            description: 'Вытяжное устройство для механической системы вентиляции',
            priceMinRub: '6 848',
            priceMaxRub: '56 584',
            priceMinEur: '77.60',
            priceMaxEur: '643.86',
        },
        {
            id: 2,
            img: '@/assets/product_big_2.png',
            title: 'G2H',
            description: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
            priceMinRub: '6 848',
            priceMaxRub: '56 584',
            priceMinEur: '77.60',
            priceMaxEur: '643.86',
        },
        {
            id: 3,
            img: '@/assets/product_big_3.png',
            title: 'GHN',
            description: 'Вытяжное устройство с датчиком присутствия',
            priceMinRub: '6 848',
            priceMaxRub: '56 584',
            priceMinEur: '77.60',
            priceMaxEur: '643.86',
        },
        {
            id: 4,
            img: '@/assets/product_big_4.png',
            title: 'TDA',
            description: 'Вытяжное устройство с датчиком присутствия',
            priceMinRub: '6 848',
            priceMaxRub: '56 584',
            priceMinEur: '77.60',
            priceMaxEur: '643.86',
        },
        {
            id: 5,
            img: '@/assets/product_big_1.png',
            title: 'BXC',
            description: 'Вытяжное устройство для механической системы вентиляции',
            priceMinRub: '6 848',
            priceMaxRub: '56 584',
            priceMinEur: '77.60',
            priceMaxEur: '643.86',
        },
        {
            id: 6,
            img: '@/assets/product_big_2.png',
            title: 'G2H',
            description: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
            priceMinRub: '6 848',
            priceMaxRub: '56 584',
            priceMinEur: '77.60',
            priceMaxEur: '643.86',
        },
        {
            id: 7,
            img: '@/assets/product_big_3.png',
            title: 'GHN',
            description: 'Вытяжное устройство с датчиком присутствия',
            priceMinRub: '6 848',
            priceMaxRub: '56 584',
            priceMinEur: '77.60',
            priceMaxEur: '643.86',
        },
        {
            id: 8,
            img: '@/assets/product_big_4.png',
            title: 'TDA',
            description: 'Вытяжное устройство с датчиком присутствия',
            priceMinRub: '6 848',
            priceMaxRub: '56 584',
            priceMinEur: '77.60',
            priceMaxEur: '643.86',
        },
        {
            id: 9,
            img: '@/assets/product_big_4.png',
            title: 'TDA',
            description: 'Вытяжное устройство с датчиком присутствия',
            priceMinRub: '6 848',
            priceMaxRub: '56 584',
            priceMinEur: '77.60',
            priceMaxEur: '643.86',
        },
        {
            id: 10,
            img: '@/assets/product_big_4.png',
            title: 'TDA',
            description: 'Вытяжное устройство с датчиком присутствия',
            priceMinRub: '6 848',
            priceMaxRub: '56 584',
            priceMinEur: '77.60',
            priceMaxEur: '643.86',
        },
    ]
})